# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cparams.proto\"w\n\x17LoadBalancingParameters\x12/\n\x12workload_parameter\x18\x01 \x03(\x0b\x32\x13.WorkloadParameters\x12+\n\x10worker_parameter\x18\x02 \x03(\x0b\x32\x11.WorkerParameters\"\x86\x01\n\x12WorkloadParameters\x12\x10\n\x05i_min\x18\x01 \x01(\x05:\x01\x31\x12\x10\n\x05i_max\x18\x02 \x01(\x05:\x01\x31\x12\x13\n\x08load_min\x18\x03 \x01(\x01:\x01\x31\x12\x13\n\x08load_max\x18\x04 \x01(\x01:\x01\x31\x12\"\n\x1a\x61llowed_worker_probability\x18\x05 \x03(\x01\"v\n\x10WorkerParameters\x12\x10\n\x05i_min\x18\x01 \x01(\x05:\x01\x31\x12\x10\n\x05i_max\x18\x02 \x01(\x05:\x01\x31\x12\x17\n\x0c\x63\x61pacity_min\x18\x03 \x01(\x01:\x01\x31\x12\x17\n\x0c\x63\x61pacity_max\x18\x04 \x01(\x01:\x01\x31\x12\x0c\n\x04\x63ost\x18\x05 \x01(\x01\"L\n\x14LoadBalancingProblem\x12\x1b\n\x08workload\x18\x01 \x03(\x0b\x32\t.Workload\x12\x17\n\x06worker\x18\x02 \x03(\x0b\x32\x07.Worker\"1\n\x08Workload\x12\x0c\n\x04load\x18\x01 \x01(\x01\x12\x17\n\x0f\x61llowed_workers\x18\x02 \x03(\x05\"(\n\x06Worker\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x01\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x01'
)




_LOADBALANCINGPARAMETERS = _descriptor.Descriptor(
  name='LoadBalancingParameters',
  full_name='LoadBalancingParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload_parameter', full_name='LoadBalancingParameters.workload_parameter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_parameter', full_name='LoadBalancingParameters.worker_parameter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=135,
)


_WORKLOADPARAMETERS = _descriptor.Descriptor(
  name='WorkloadParameters',
  full_name='WorkloadParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i_min', full_name='WorkloadParameters.i_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_max', full_name='WorkloadParameters.i_max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load_min', full_name='WorkloadParameters.load_min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load_max', full_name='WorkloadParameters.load_max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowed_worker_probability', full_name='WorkloadParameters.allowed_worker_probability', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=272,
)


_WORKERPARAMETERS = _descriptor.Descriptor(
  name='WorkerParameters',
  full_name='WorkerParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i_min', full_name='WorkerParameters.i_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_max', full_name='WorkerParameters.i_max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity_min', full_name='WorkerParameters.capacity_min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity_max', full_name='WorkerParameters.capacity_max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='WorkerParameters.cost', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=392,
)


_LOADBALANCINGPROBLEM = _descriptor.Descriptor(
  name='LoadBalancingProblem',
  full_name='LoadBalancingProblem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload', full_name='LoadBalancingProblem.workload', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker', full_name='LoadBalancingProblem.worker', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=470,
)


_WORKLOAD = _descriptor.Descriptor(
  name='Workload',
  full_name='Workload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='load', full_name='Workload.load', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowed_workers', full_name='Workload.allowed_workers', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=521,
)


_WORKER = _descriptor.Descriptor(
  name='Worker',
  full_name='Worker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capacity', full_name='Worker.capacity', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='Worker.cost', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=563,
)

_LOADBALANCINGPARAMETERS.fields_by_name['workload_parameter'].message_type = _WORKLOADPARAMETERS
_LOADBALANCINGPARAMETERS.fields_by_name['worker_parameter'].message_type = _WORKERPARAMETERS
_LOADBALANCINGPROBLEM.fields_by_name['workload'].message_type = _WORKLOAD
_LOADBALANCINGPROBLEM.fields_by_name['worker'].message_type = _WORKER
DESCRIPTOR.message_types_by_name['LoadBalancingParameters'] = _LOADBALANCINGPARAMETERS
DESCRIPTOR.message_types_by_name['WorkloadParameters'] = _WORKLOADPARAMETERS
DESCRIPTOR.message_types_by_name['WorkerParameters'] = _WORKERPARAMETERS
DESCRIPTOR.message_types_by_name['LoadBalancingProblem'] = _LOADBALANCINGPROBLEM
DESCRIPTOR.message_types_by_name['Workload'] = _WORKLOAD
DESCRIPTOR.message_types_by_name['Worker'] = _WORKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadBalancingParameters = _reflection.GeneratedProtocolMessageType('LoadBalancingParameters', (_message.Message,), {
  'DESCRIPTOR' : _LOADBALANCINGPARAMETERS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:LoadBalancingParameters)
  })
_sym_db.RegisterMessage(LoadBalancingParameters)

WorkloadParameters = _reflection.GeneratedProtocolMessageType('WorkloadParameters', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADPARAMETERS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadParameters)
  })
_sym_db.RegisterMessage(WorkloadParameters)

WorkerParameters = _reflection.GeneratedProtocolMessageType('WorkerParameters', (_message.Message,), {
  'DESCRIPTOR' : _WORKERPARAMETERS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:WorkerParameters)
  })
_sym_db.RegisterMessage(WorkerParameters)

LoadBalancingProblem = _reflection.GeneratedProtocolMessageType('LoadBalancingProblem', (_message.Message,), {
  'DESCRIPTOR' : _LOADBALANCINGPROBLEM,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:LoadBalancingProblem)
  })
_sym_db.RegisterMessage(LoadBalancingProblem)

Workload = _reflection.GeneratedProtocolMessageType('Workload', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOAD,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Workload)
  })
_sym_db.RegisterMessage(Workload)

Worker = _reflection.GeneratedProtocolMessageType('Worker', (_message.Message,), {
  'DESCRIPTOR' : _WORKER,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Worker)
  })
_sym_db.RegisterMessage(Worker)


# @@protoc_insertion_point(module_scope)
