# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cparams.proto\"{\n\x12KnapsackParameters\x12\x10\n\x05\x62_min\x18\x01 \x01(\x05:\x01\x31\x12\x10\n\x05\x62_max\x18\x02 \x01(\x05:\x01\x31\x12\r\n\x05\x66_min\x18\x03 \x03(\x01\x12\r\n\x05\x66_max\x18\x04 \x03(\x01\x12#\n\nitem_param\x18\x05 \x03(\x0b\x32\x0f.ItemParameters\"v\n\x0eItemParameters\x12\x10\n\x05i_min\x18\x01 \x01(\x05:\x01\x31\x12\x10\n\x05i_max\x18\x02 \x01(\x05:\x01\x31\x12\x10\n\x05\x63_min\x18\x03 \x01(\x05:\x01\x31\x12\x10\n\x05\x63_max\x18\x04 \x01(\x05:\x01\x31\x12\r\n\x05\x64_min\x18\x05 \x03(\x01\x12\r\n\x05\x64_max\x18\x06 \x03(\x01\"=\n\x08Knapsack\x12\t\n\x01r\x18\x01 \x01(\x05\x12\x11\n\x03\x62in\x18\x02 \x03(\x0b\x32\x04.Bin\x12\x13\n\x04item\x18\x03 \x03(\x0b\x32\x05.Item\"\x10\n\x03\x42in\x12\t\n\x01s\x18\x01 \x03(\x01\"\x1c\n\x04Item\x12\t\n\x01\x63\x18\x01 \x01(\x05\x12\t\n\x01\x64\x18\x02 \x03(\x01'
)




_KNAPSACKPARAMETERS = _descriptor.Descriptor(
  name='KnapsackParameters',
  full_name='KnapsackParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b_min', full_name='KnapsackParameters.b_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_max', full_name='KnapsackParameters.b_max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f_min', full_name='KnapsackParameters.f_min', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f_max', full_name='KnapsackParameters.f_max', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_param', full_name='KnapsackParameters.item_param', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=139,
)


_ITEMPARAMETERS = _descriptor.Descriptor(
  name='ItemParameters',
  full_name='ItemParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i_min', full_name='ItemParameters.i_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i_max', full_name='ItemParameters.i_max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c_min', full_name='ItemParameters.c_min', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c_max', full_name='ItemParameters.c_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_min', full_name='ItemParameters.d_min', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_max', full_name='ItemParameters.d_max', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=259,
)


_KNAPSACK = _descriptor.Descriptor(
  name='Knapsack',
  full_name='Knapsack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='Knapsack.r', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bin', full_name='Knapsack.bin', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item', full_name='Knapsack.item', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=322,
)


_BIN = _descriptor.Descriptor(
  name='Bin',
  full_name='Bin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='Bin.s', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=340,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='Item.c', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='Item.d', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=370,
)

_KNAPSACKPARAMETERS.fields_by_name['item_param'].message_type = _ITEMPARAMETERS
_KNAPSACK.fields_by_name['bin'].message_type = _BIN
_KNAPSACK.fields_by_name['item'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['KnapsackParameters'] = _KNAPSACKPARAMETERS
DESCRIPTOR.message_types_by_name['ItemParameters'] = _ITEMPARAMETERS
DESCRIPTOR.message_types_by_name['Knapsack'] = _KNAPSACK
DESCRIPTOR.message_types_by_name['Bin'] = _BIN
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KnapsackParameters = _reflection.GeneratedProtocolMessageType('KnapsackParameters', (_message.Message,), {
  'DESCRIPTOR' : _KNAPSACKPARAMETERS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:KnapsackParameters)
  })
_sym_db.RegisterMessage(KnapsackParameters)

ItemParameters = _reflection.GeneratedProtocolMessageType('ItemParameters', (_message.Message,), {
  'DESCRIPTOR' : _ITEMPARAMETERS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:ItemParameters)
  })
_sym_db.RegisterMessage(ItemParameters)

Knapsack = _reflection.GeneratedProtocolMessageType('Knapsack', (_message.Message,), {
  'DESCRIPTOR' : _KNAPSACK,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Knapsack)
  })
_sym_db.RegisterMessage(Knapsack)

Bin = _reflection.GeneratedProtocolMessageType('Bin', (_message.Message,), {
  'DESCRIPTOR' : _BIN,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Bin)
  })
_sym_db.RegisterMessage(Bin)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
